##############################
#### INTERFACE PARAMETERS ####
##############################
interface:
  theme: theme-dark
  transition:
    page: 200
#########################
#### GAME PARAMETERS ####
#########################
game:
  tolerance:
    flag: 500
    target: 200
    pitfall: 500
  penalty:
    pitfall: 100
  speed: 5000

#############################
#### TUTORIAL DEFINITION ####
#############################
tutorial:
  start:
    zoom: 5
    center: [ 270845.15, 5904541.30 ]
  player: [ 396377.1, 5701254.9 ]
  target: [ 416553.587, 5708562.378 ]
  hints:
    0: You are in the west of the city of Lyon
    6: You are between St-Étienne and Clermont-Ferrand
    8: You are south-west of Ambert
    10: You are between St-Amant-Roche-Savine and St-Germain-l'Herm
    11: You are south-west of Fournols
    13: You are in La Colombière, double-tap on your position
###########################
#### LEVELS DEFINITION ####
###########################
levels:
  - 1