##############################
#### INTERFACE PARAMETERS ####
##############################
interface:
  theme: theme-dark
  transition:
    page: 200
#########################
#### GAME PARAMETERS ####
#########################
game:
  score:
    increments:
      default: 1
      movement: 1
    intervals:
      default: 100
      movement: 20
    modifiers:
      pitfalls: 200
      bonus: -100
  tolerance:
    flag: 500
    target: 200
    pitfalls: 500
    bonus: 200
  speed: 5000
  routing: 13.5
###########################
#### FORM DEFINITION ######
###########################
form:
  - question: 'Gender (select all relevant answers):'
    mandatory: false
    multiple: true
    answers:
      - text: Woman
        unique: false
      - text: Man
        unique: false
      - text: Transgender
        unique: false
      - text: Prefer not to answer
        unique: true
  - question: 'Select your age category:'
    mandatory: false
    multiple: false
    answers:
      - text: 18-24
        unique: true
      - text: 25-34
        unique: true
      - text: 35-44
        unique: true
      - text: 45-59
        unique: true
      - text: 60 and above
        unique: true
      - text: Prefer not to answer
        unique: true
  - question: 'You use interactive maps:'
    mandatory: false
    multiple: false
    answers:
      - text: Every day
        unique: true
      - text: A few times a week
        unique: true
      - text: A few times a month
        unique: true
      - text: Almost never
        unique: true
      - text: Prefer not to answer
        unique: true

#############################
#### TUTORIAL DEFINITION ####
#############################
tutorial:
  start:
    zoom: 5
    center: [ 270845.15, 5904541.30 ]
  player: [ 396377.1, 5701254.9 ]
  target: [ 416553.587, 5708562.378 ]
  hints:
    0: You are in the west of the city of Lyon
    6: You are between St-Étienne and Clermont-Ferrand
    8: You are south-west of Ambert
    10: You are between St-Amant-Roche-Savine and St-Germain-l'Herm
    11: You are south-west of Fournols
    13: You are in La Colombière, double-tap on your position
  pitfalls:
    - [ 399537.1, 5699198.9 ]
    - [ 399416.53, 5703120.31 ]
    - [ 402172.7, 5700144.5 ]
    - [ 404291.06, 5700146.56 ]
    - [ 407776.7, 5703492.8 ]
    - [ 411222.6, 5703538.6 ]
    - [ 415029.6, 5707542.2 ]
    - [ 402876.1, 5707401.3 ]
    - [ 404785.3, 5711359.4 ]
    - [ 405730.7, 5706364.3 ]
    - [ 411794.4, 5707942.2 ]
    - [ 409265.0, 5709098.6 ]
###########################
#### LEVELS DEFINITION ####
###########################
levels:
  - start:
      zoom: 5
      center: [ 270845.15, 5904541.30 ]
    player: [ 396377.1, 5701254.9 ]
    target: [ 416553.587, 5708562.378 ]
    hints:
      0: You are in the west of the city of Lyon
      6: You are between St-Étienne and Clermont-Ferrand
      8: You are south-west of Ambert
      10: You are between St-Amant-Roche-Savine and St-Germain-l'Herm
      11: You are south-west of Fournols
      13: You are in La Colombière, double-tap on your position
    pitfalls:
      - [ 399537.1, 5699198.9 ]
      - [ 399416.53, 5703120.31 ]
      - [ 402172.7, 5700144.5 ]
      - [ 404291.06, 5700146.56 ]
      - [ 407776.7, 5703492.8 ]
      - [ 411222.6, 5703538.6 ]
      - [ 415029.6, 5707542.2 ]
      - [ 402876.1, 5707401.3 ]
      - [ 404785.3, 5711359.4 ]
      - [ 405730.7, 5706364.3 ]
      - [ 411794.4, 5707942.2 ]
      - [ 409265.0, 5709098.6 ]
    bonus:
      - [ 398112.1, 5703642.2 ]
      - [ 400818.1, 5698171.1 ]
      - [ 402239.3, 5705426.3 ]
      - [ 406444.5, 5701153.8 ]
      - [ 409983.0, 5702743.2 ]
      - [ 406771.2, 5708716.8 ]
      - [ 413894.2, 5705047.0 ]
      - [ 415196.3, 5709601.9 ]
      - [ 416592.9, 5703133.2 ]