##############################
#### INTERFACE PARAMETERS ####
##############################
interface:
  theme: theme-dark
  transition:
    page: 500
  languages:
    available:
      - fr
      - en
    current: en
  map:
    levels: [-571380.89, 5066464.36, 1064167.68, 6636793.32]
    start:
      ## center: [ 291041.84, 5629996.16 ]
      ## zoom: 15
      centers:
        # Bordeaux
        - [ -64684, 5597363 ]
        # Toulouse
        - [ 159999, 5403967 ]
        # Marseille
        - [ 598670, 5357182 ]
        # Nice
        - [ 808274, 5420192 ]
        # Lyon
        - [ 540608, 5740682 ]
        # Clermont-Ferrand
        - [ 343282, 5744757 ]
        # Limoges
        - [ 140209, 5753379 ]
        # Nantes
        - [ -172696, 5977771 ]
        # Rennes
        - [ -185502, 6124747 ]
        # Brest
        - [ -499316, 6172477 ]
        # Paris
        - [ 261063, 6250622 ]
        # Cherbourg
        - [ -180518, 6383773 ]
        # Le Havre
        - [ 13424, 6359689 ]
        # Lille
        - [ 340335, 6558251 ]
        # Amiens
        - [ 254770, 6429320 ]
        # Strasbourg
        - [ 862753, 6203037 ]
        # Nancy
        - [ 689293, 6222391 ]
        # Reims
        - [ 449185, 6319016 ]
        # Orléans
        - [ 212205, 6090695 ]
      zoom: 7
#########################
#### GAME PARAMETERS ####
#########################
game:
  score:
    increments:
      default: 1
      movement: 1
    intervals:
      default: 100
      movement: 20
    modifiers:
      pitfalls: 500
      bonus: -250
  tolerance:
    flag: 500
    target: 200
    pitfalls: 500
    bonus: 200
  visibility:
    bonus: 1500
  speed:
    travel: 5000 # in km/h
    roaming: 20 # in px/s
  routing: 13.5
###########################
#### FORM DEFINITION ######
###########################
form:
  - question: 'Genre<br>(Sélectionnez les réponses applicables)'
    mandatory: false
    multiple: true
    answers:
      - text: Femme
        unique: false
      - text: Homme
        unique: false
      - text: Trans
        unique: false
      - text: Ne se prononce pas
        unique: true
  - question: 'Catégorie d''âge'
    mandatory: false
    multiple: false
    answers:
      - text: 18-24
        unique: true
      - text: 25-34
        unique: true
      - text: 35-44
        unique: true
      - text: 45-59
        unique: true
      - text: 60 et plus
        unique: true
      - text: Ne se prononce pas
        unique: true
  - question: 'Vous utilisez une carte interactive<br>(Google Maps, Apple Maps, OpenStreetMap, etc.)'
    mandatory: false
    multiple: false
    answers:
      - text: Tous les jours
        unique: true
      - text: Plusieurs fois par semaine
        unique: true
      - text: Plusieurs fois par mois
        unique: true
      - text: Presque jamais
        unique: true
      - text: Ne se prononce pas
        unique: true
consent:
  - type: paragraph
    content: 'J''accepte que mes données de jeux
      soient collectées et utilisées par l''équipe LostInZoom
      afin de mieux comprendre comment nous naviguons dans
      les cartes interactives.'
  - type: list
    title: 'Les données suivantes sont collectées:'
    content:
      - 'Les réponses aux formulaires sociologiques et cognitifs.'
      - 'Le métriques de jeux, à savoir le temps passé, le score et la distance parcourue par niveau.'
      - 'Les interactions avec la carte pendant un niveau, à savoir les déplacements latéraux,
        les zooms en avant et en arrière.'
      - 'Les informations sur votre appareil, à savoir le type (téléphone mobile ou tablette),
        le système d''exploitation (Android, iOS, etc.) et taille de l''écran.'
  - type: paragraph
    content: 'Nous ne collectons aucune information personnelle tel que votre nom, votre
      localisation ou votre adresse IP.'
  - type: paragraph
    content: 'Les données collectées ne seront jamais dévoilées au-delà de notre équipe
      de recherche. Ceci étant dit, nous les utiliserons pour conduire des analyses
      statistiques, et les résultats de ces analyses pourront être sujets à une ou
      plusieurs publications scientifiques.'
  - type: paragraph
    content: 'En signant ce formulaire et en continuant le jeu, vous comprenez et acceptez
      de partager ces données avec notre équipe.'
#############################
#### TUTORIAL DEFINITION ####
#############################
tutorial:
  start:
    zoom: 5
    center: [ 270845.15,5904541.30 ]
  player: [ 396377.1,5701254.9 ]
  target: [ 416553.587,5708562.378 ]
  hints:
    0: À l'ouest de la ville de Lyon
    6: Entre St-Étienne et Clermont-Ferrand
    8: Au sud-ouest de la ville d'Ambert
    10: Entre St-Amant-Roche-Savine et St-Germain-l'Herm
    11: Au sud-ouest de Fournols
    13: Au hameau de La Colombière, double-cliquez sur votre position
  pitfalls:
    - [ 399537.1,5699198.9 ]
    - [ 399416.53,5703120.31 ]
    - [ 402172.7,5700144.5 ]
    - [ 404291.06,5700146.56 ]
    - [ 407776.7,5703492.8 ]
    - [ 411222.6,5703538.6 ]
    - [ 415029.6,5707542.2 ]
    - [ 402876.1,5707401.3 ]
    - [ 404785.3,5711359.4 ]
    - [ 405730.7,5706364.3 ]
    - [ 411794.4,5707942.2 ]
    - [ 409265.0,5709098.6 ]
  bonus:
    - [ 398112.1,5703642.2 ]
    - [ 400818.1,5698171.1 ]
    - [ 402239.3,5705426.3 ]
    - [ 406444.5,5701153.8 ]
    - [ 409983.0,5702743.2 ]
    - [ 406771.2,5708716.8 ]
    - [ 413894.2,5705047.0 ]
    - [ 415196.3,5709601.9 ]
    - [ 416592.9,5703133.2 ]
###########################
#### LEVELS DEFINITION ####
###########################
levels:
  - type: tier
    content:
      - minimap: [ -216509, 6127212 ]
        start:
          zoom: 5
          center: [ 270845.15,5904541.30 ]
        player: [ -345683.0352282714,6152332.792990951 ]
        target: [ -330178.07675322174,6117700.949246099 ]
        hints:
          0: You are in the west of the city of Rennes
          6: You are between Lorient and St-Brieuc
          8: You are north of Pontivy
          10: You are between Gouarec and Corlay 
          11: You are in St-Igeaux, double-tap on your position
        pitfalls:
          - [ -354074.93805303966,6144738.938691721 ]
          - [ -332481.4775624775,6140267.372537037 ]
          - [ -344400.87666069705,6143449.063839415 ]
          - [ -335734.18440183485,6135249.425198436 ]
          - [ -351021.59005887026,6129287.336992194 ]
          - [ -341830.0374075777,6127491.066827488 ]
          - [ -332347.0685859482,6128508.634766536 ]
          - [ -334591.7497707198,6149519.8148358 ]
          - [ -341543.72823042,6136346.942591847 ]
        bonus:
          - [ -348074.6313326531,6140114.498480472 ]
          - [ -350367.3899996354,6142681.833370734 ]
          - [ -348173.4528687405,6134202.100545352 ]
          - [ -339571.33420276106,6146127.96639936 ]
          - [ -336542.5169569605,6118925.938958378 ]
          - [ -343359.71517578105,6139266.790875086 ]
          - [ -333120.44969174766,6121170.003909771 ]
          - [ -326402.71403488476,6130024.302039234 ]
          - [ -357192.19324065116,6140933.410330648 ]
          - [ -335082.7828091639,6141802.881527393 ]
      - minimap: [ 213178, 6110557 ]
      - minimap: [ 527949, 5779132 ]
      - minimap: [ -43302, 5637568 ]
  - type: test
    name: "Expérience 1"
  - type: tier
    content:
      - minimap: [ 143229, 5447706 ]
      - minimap: [ 677841, 5767473 ]
      - minimap: [ 151556, 5772470 ]
      - minimap: [ -169876, 6368703 ]
  - type: test
    name: "Expérience 2"
  - type: tier
    content:
      - minimap: [ 143229, 5447706 ]
      - minimap: [ 677841, 5767473 ]
      - minimap: [ 151556, 5772470 ]
      - minimap: [ -169876, 6368703 ]
  - type: test
    name: "Expérience 3"
  - type: tier
    content:
      - minimap: [ 143229, 5447706 ]
      - minimap: [ 677841, 5767473 ]
      - minimap: [ 151556, 5772470 ]
      - minimap: [ -169876, 6368703 ]